@baseUrl = http://localhost:5000
@urlPath = api/v1

###
PUT {{baseUrl}}/{{urlPath}}/user/block/63da85d6007a130969e091ca
Content-Type: application/json
Accept: application/json
withCredentials: true

###
PUT {{baseUrl}}/{{urlPath}}/user/unblock/63da85d6007a130969e091ca
Content-Type: application/json
Accept: application/json
withCredentials: true
