@baseUrl = http://localhost:5000
@urlPath = api/v1

###
GET {{baseUrl}}/{{urlPath}}/post/comments/63c7d025ff906f535557b455
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/post/commentsnames/63c7d025ff906f535557b455
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/post/single/comment/63c7d025ff906f535557b455/63d8fdb6d774895545d737e3
Content-Type: application/json
Accept: application/json
withCredentials: true

###
POST {{baseUrl}}/{{urlPath}}/post/comment
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "userTo": "63bb0f353773a318b6c42e61",
  "postId": "63c7d025ff906f535557b455",
  "comment": "Hi",
  "profilePicture": ""
}
